export default {
    to: "/dashboard/fixed-assets",
    order: 3,
    icon: "mdi-propane-tank",
    title: "Fixed Assets",
    disabled: false,
    value: 0,
    sublinks: [
        {
            to: "/dashboard/assets/listing",
            order: 3,
            icon: "mdi-format-indent-increase",
            title: "Listings",
            disabled: false,
            value: 0,
        },
        {
            to: "/dashboard/assets/card",
            order: 3,
            icon: "mdi-layers-plus",
            title: "Add Asset",
            disabled: false,
            value: 0,
        },
        {
            to: "/dashboard/assets/ready-for-transfer/listing",
            order: 3,
            icon: "mdi-transfer",
            title: "Ready To Transfer",
            disabled: false,
            value: 0,
        },
        {
            to: "/dashboard/assets/pending-for-transfer-approval/listing",
            order: 3,
            icon: "mdi-lan-pending",
            title: "Pending Approval",
            disabled: false,
            value: 0,
        },
        {
            to: "/dashboard/assets/rejected-transfer/listing",
            order: 3,
            icon: "mdi-stop",
            title: "Rejected Transfer",
            disabled: false,
            value: 0,
        },
        {
            to: "/dashboard/assets/complete-transfer/listing",
            order: 3,
            icon: "mdi-ticket-confirmation",
            title: "Complete Checkouts",
            disabled: false,
            value: 0,
        },
    ],
}
